name: Videojuegos

services:
  app:
    build: .
    container_name: app
    ports:
      - "8080:3000"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: miapp
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass

